### ISSUE TITLE
Fails to process jsx file if there are multiple file extensions in the extensions array

### ISSUE THREAD

**Issue by bbstilson** [aMarCruz/rollup-plugin-cleanup#1]
For example, while processing this file:

```javascript
import React, { Component } from 'react';

export default class App extends Component {
    render() {
        return (
            <h1>Some super important stuff.</h1>
        );
    }
}
```

with the options set like so: 
```javascript
cleanup({
    extensions: ['.jsx']
})
```

it works fine. But if I add `.js`:
```javascript
cleanup({
    extensions: ['.js', '.jsx']
})
```

It fails to compile and complains about an unexpected token (the jsx)

**Comment by aMarCruz** [comment]
@bbstilson I will fix this issue asap.
Thanks for you feed-back.

**Comment by aMarCruz** [comment]
@bbstilson , I made some tests and I think the error is in the order of your plugins.

Please test with something like:

```js
rollup({
  entry: 'src/main.js',
  plugins: [
    jsx(),
    cleanup()
  ]
}).then(...)
```

It is working for me, this is because cleanup is a post-processor that only handles JS.
I'll update the README noting this behavior.

**Comment by aMarCruz** [comment]
v0.1.3 is out, closing this issue now.
