### ISSUE TITLE
Errors out on spread operator

### ISSUE THREAD

**Issue by andreas-wagner** [aMarCruz/rollup-plugin-cleanup#10]
[!] (cleanup plugin) SyntaxError: Unexpected token (14:18)

Line of the file:
      info.push({ ...profiles.splice(pos, 1)[0].output, index });

Char 18 is the space before the three dots...

**Comment by aMarCruz** [comment]
@andreas-wagner , thanks by your report, I will check this ASAP.

**Comment by aMarCruz** [comment]
@andreas-wagner please make sure that rollup-plugin-cleanup is at the end of the plugin list, as mentioned in [the README](https://github.com/aMarCruz/rollup-plugin-cleanup#rollup-plugin-cleanup):

> Because rollup is a JavaScript bundler and cleanup is a JavaScript post-processor, it should work with any JavaScript dialect handled by rollup, but you need put cleanup last in your plugin list.

**Comment by andreas-wagner** [comment]
Hi, it is the only plugin that I use, actually I just wanted to strip away comments...

**Comment by aMarCruz** [comment]
v3.0.0-Beta.1 is in npm now. This has support for the spread operator in objects (ES2018). Please try it.

**Comment by andreas-wagner** [comment]
Works like a charm. Thank you for the quick update :-)
