### ISSUE TITLE
Not cleaning up properly /**/ comments

### ISSUE THREAD

**Issue by fab1o** [aMarCruz/rollup-plugin-cleanup#12]
input examples:
```
   return function (/* ...args */) {
    return fn.apply(that, arguments);
  };
 ....
 catch (e) { /* empty */ }
```

output:
```
  return function (             ) {
    return fn.apply(that, arguments);
  };
 ....
 catch (e) {             }
```

expected:
```
  return function () {
    return fn.apply(that, arguments);
  };
  ....
  catch (e) {}
```

**Comment by aMarCruz** [comment]
@fab1o good catch.
Currently, the deletion of comments is done in 2 phases, in the first the comments are replaced with spaces, in the second the trailing spaces are removed and the blank lines are compacted.

This simplifies the use of MagicString (the library that generates the sourceMaps), but it causes the effect you mention.
I am not sure there is a simple way to compact these comments without changing the logic of the library, but if there is, I will implement it.

Thanks for your feedback.

**Comment by aMarCruz** [comment]
@fab1o sorry, I think this issue is not serious but its solution requires refactoring of the plugin and I do not have enough time to do it.

Anyway, PRs are welcome.

**Comment by aMarCruz** [comment]
@fab1o , v3.1.0 released today is fixing this issue.
