### ISSUE TITLE
comments: 'none' not removing all comments

### ISSUE THREAD

**Issue by mebibou** [aMarCruz/rollup-plugin-cleanup#14]
My plugins section looks like this:
```js
plugins: [
    typescript({
      typescript: require('typescript'),
      importHelpers: true
    }),
    hypothetical({
      allowFallthrough: true
    }),
    resolve(),
    commonJS({
      include: 'node_modules/**'
    }),
    buble(),
    cleanup({
      comments: 'none'
    })
  ]
```

but in the output code I have things like this:
```js
  // check type
...
  /**
   * blablabla
   */
```
I basically want to remove any kind of comment, is it possible with this plugin?

**Comment by aMarCruz** [comment]
@mebibou , sorry by the delay.
Looks like cleanup is ignoring the files.
Please add TS extensions in your config:

 ```
  cleanup({
    comments: 'none',
    extensions: ['js', 'jsx', 'ts', 'tsx'],
  })
```

ping me if this does not work.

**Comment by mebibou** [comment]
Oh yes that works, since I put the plugin after the transpiling I thought it would clean up the output file not the source, my bad

**Comment by aMarCruz** [comment]
@mebibou , the plugin is cleaning the transpiled file, but Rollup keeps the .ts extension on it.
Thanks for your feedback
