### ISSUE TITLE
How to remove specific comments?

### ISSUE THREAD

**Issue by SidKwok** [aMarCruz/rollup-plugin-cleanup#2]
Any options?

**Comment by aMarCruz** [comment]
@SidKwok , currently, cleanup has no option to remove specific comments, only to keep them.

Example:
this will remove ALL comments except for JSDoc (that contains an '@' followed by an alpha letter), ESLint directives, and comments starting with "--":

```js
// the first character received by the regex is either '*' or '/'
cleanup({ comments: ['jsdoc', 'eslint', /\*--/] })
```

so, in this fragment the last comment will be removed:
```js
/** @license MIT */
/* global foo */
/*-- comment 1 (preserved) */
//-- comment 2 (removed)
```

**Comment by SidKwok** [comment]
Will it be the new feature in the next version?
I would like to keep the jsdoc in my output library.I will also write `/*@file description*/` in my module file, but they seem not really necessary in the library.
I think such feature is really helpful.

**Comment by aMarCruz** [comment]
@SidKwok the example of my previous comment must to work in the current version. I don't know yet if the next version will have exclusion.

As you can see in the regexes of the [Predefined filters](https://github.com/aMarCruz/rollup-plugin-cleanup#predefined-filters), the default is to keep _any_ comment having "@licence", "@preserve", or "@cc_on". To keep jsdoc in your code use the `comments: ['jsdoc']` option.

(be aware that the standard jsdoc comments begins with two asterisks: `/**@file description*/` is valid, `/*@file description*/` is not)

**Comment by aMarCruz** [comment]
v1.0.0 is out with the current filter behavior.

**Comment by SidKwok** [comment]
how can I use the feature? I didn't see any instructions in the newest doc.
