### ISSUE TITLE
Is this plugin still maintained?

### ISSUE THREAD

**Issue by ejdzipi** [aMarCruz/rollup-plugin-cleanup#23]
Hello,
i would like to ask, if this plugin is still maintained. It still includes rollup ^0.x dependency and so on.
Thanks

**Comment by rjgamer** [comment]
It would be also nice, to get this plugin as an official rollup plugin.

**Comment by aMarCruz** [comment]
@ejdzipi , v3.2.0 is in npm now.
@rjgamer I have no problem with that.

Closing...
