### ISSUE TITLE
maxEmptyLines doesn't seem to work

### ISSUE THREAD

**Issue by DxCx** [aMarCruz/rollup-plugin-cleanup#3]
Hi,

I'm trying to use your plugin,
cleaning comments seems to work, however, maxEmptyLines doesn't.
tried to use both 0 and then 1, however the output is the same. (10+ empty lines)

Thanks!

**Comment by aMarCruz** [comment]
@DxCx hi.
Please show the file and the rollup.config.js that generates the issue?

In [my tests](https://github.com/aMarCruz/rollup-plugin-cleanup/blob/0b147fbc2d080e9fd5509efd7552143a2e452f47/test/index.js#L76-L85) `maxEmptyLines` is working Ok.

**Comment by DxCx** [comment]
well i was trying to see graphql-js's bundled size.
so i setup rullup, with babel, to compile the src directory of this repo:
https://github.com/graphql/graphql-js

so essentially it looks like:
```javascript
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';
import cleanup from 'rollup-plugin-cleanup';
import filesize from 'rollup-plugin-filesize';
import progress from 'rollup-plugin-progress';

export default {
    entry: 'graphql/src/index.js',
    format: 'cjs',
    plugins: [
      filesize(),
      progress(),
      nodeResolve({ jsnext: true, module: true }),
      commonjs({
        include: 'node_modules/**',
      }),
      babel({
        babelrc: false,
        runtimeHelpers: true,
        plugins: [
          [test.hackPlugin],
          "syntax-async-functions",
          "transform-class-properties",
          "transform-flow-strip-types",
          "transform-object-rest-spread",
          "transform-es2015-template-literals",
          "transform-es2015-literals",
          "transform-es2015-function-name",
          "transform-es2015-arrow-functions",
          "transform-es2015-block-scoped-functions",
          ["transform-es2015-classes", {loose: true}],
          "transform-es2015-object-super",
          "transform-es2015-shorthand-properties",
          "transform-es2015-duplicate-keys",
          "transform-es2015-computed-properties",
          "check-es2015-constants",
          ["transform-es2015-spread", {loose: true}],
          "transform-es2015-parameters",
          ["transform-es2015-destructuring", {loose: true}],
          "transform-es2015-block-scoping",
          "transform-regenerator",
          "transform-es3-property-literals",
          "external-helpers",
        ],
      }),
      cleanup({
        maxEmptyLines: 1,
        comments: "none",
      }),
    ],
    dest: 'dist/bundle.js',
    external: ['iterall'],
};
```

**Comment by aMarCruz** [comment]
@DxCx , it is working, but not as you want.
cleanup processes file by file and rollup concatenates them in a final stage, inseting blank lines between files.
Even more, it seems that the first block of bundle.js (containing `classCallCheck`) is inserted after cleanup did its job.

I did a test with `maxEmptyLines:0` and the output is ok inside each file.

Example in original graphql/src/lenguage/lexer.js:
![image](https://cloud.githubusercontent.com/assets/6636980/22520788/544a948a-e87b-11e6-9553-04f41b8b1f26.png)

output in dist/bundle.js:
![image](https://cloud.githubusercontent.com/assets/6636980/22520837/7eade59c-e87b-11e6-89ea-75a09e0d162b.png)

To act on the generated bundle, it is necessary for cleanup to work in the last rollup phase, for which it has no support, but this is something I have planned for the next minor version that will be released soon.

I will close this issue now and will ping you when the next version is ready.
Thanks for your feedback!

**Comment by DxCx** [comment]
sure, thanks for the support @aMarCruz :)
