### ISSUE TITLE
when i use comments: 'none', but comments still removed

### ISSUE THREAD

**Issue by bluelovers** [aMarCruz/rollup-plugin-cleanup#31]
when i use comments: 'none', but comments still removed

**Comment by backspaces** [comment]
Hi @bluelovers: I'm new to this and made the same assumption: "none" meant to _remove_ none.
But it really means to _leave_ none.

Have you tried "all"?

**Comment by aMarCruz** [comment]
Maybe it's counterintuitive but yes, it's **leaving** none.
I will update the documents soon
