### ISSUE TITLE
Maintain comments starting with /*!

### ISSUE THREAD

**Issue by jhabdas** [aMarCruz/rollup-plugin-cleanup#4]
It's normal for post-processors working on code to maintain comment blocks which start with `/*!` (note the `!`). Take a look as jQuery sizzle or other popular libraries, and you'll see this. Please consider adding or just close this. Thanks!

**Comment by jhabdas** [comment]
Also, thanks for the plug-in. It's lovely 😄

**Comment by aMarCruz** [comment]
@jhabdas thanks to you! ...I'll take a look at your recommendation, I think there will be no problem adding a predefined filter for it in the next version.

In the mean time, you can use the regex `/\*!/`, like in this example:

```js
  ...
  plugins {
    cleanup({
      comments: [ 'some', /\*!/ ]
    })
```

Please note: comments[] will overwrite de default filters (it is not additive).
I hope this help and will close this issue.

**Comment by jhabdas** [comment]
Excellent. I didn't know there was a workaround. I'd like to use this plug-in in combination with the minify plugin but my comments were getting clobbered for some reason so I've switched for now. Here's my current implementation: https://github.com/jhabdas/fetch-inject/blob/master/rollup.config.js

I would prefer to keep an abbreviated license field in the dist but have not yet found a way to do so using either plugin. Cheers and thanks again for considering my proposal.

**Comment by aMarCruz** [comment]
@jhabdas , try this:

```js
  ...
  plugins {
    cleanup({
      comments: [ 'some', /^\*!/, /MIT License/ ]
    })
```

**Comment by jhabdas** [comment]
@aMarCruz Thank you :). Gave it a shot, only problem is I'm using IIFE and the end result is something like:

```
var fetchInject = (function () {
'use strict';

const script = (function(i,s,o,g,r,a,m){a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.appendChild(s.createTextNode(g));a.onload=r;m.parentNode.insertBefore(a,m);});
const style = (function(i,s,o,g,r,a,m){a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.type='text/css';a.appendChild(s.createTextNode(g));m.parentNode.insertBefore(a,m);});

/*!
 * Copyright (c) 2017 Josh Habdas
 * @license MIT
 */
var fetchInject = function (urls) {
```

Given I'm trying to use uglify with this package, and it provides support, I'll see if I can get that working instead. Thanks again!
