### ISSUE TITLE
Rollup.js: cleanup didn't generate a sourcemap for the transformation

### ISSUE THREAD

**Issue by joelpurra** [aMarCruz/rollup-plugin-cleanup#5]
I am using `cleanup` for four rollup'ed files in the same project; they share `cleanup` logic by importing the same configuration. Two of the files worked as intended, two gave the same sourcemap warning. Here's my `cleanup` configuration.

```javascript
cleanup({
    maxEmptyLines: -1,
    comments: [
        // NOTE: remove per-file copyright notices. It will be re-added as a single banner.
        // NOTE: keeping everything else not matching.
        /^(?!\*\s*This file is part of Talkie)/,
    ],
})
```

Narrowed down the issue to having files missing the (correctly formatted) license notice, which was of course positive as it's an improvement for my code.

As my regexp is basically inverted, blocking if the pattern is found, it meant that *if all comments matched*, then the below warning was given. Does that make sense? Either way, this shows that there are cases where `cleanup` will generate the below sourcemap warning.

See the original files in the Talkie, [text-to-speech for the browser](https://joelpurra.com/projects/talkie/) and specifically look at the [commit adding `cleanup`](https://github.com/joelpurra/talkie/commit/8680a298152a7c0e5a1542ae43fbc369fc5eab85) as well as the [commit fixing the warning by formatting/adding the copyright notice](https://github.com/joelpurra/talkie/commit/aa08b7e339dbdc828f7a385f3001f247535cdb34).

---

Original rollup.js warning:

> ⚠️   Sourcemap is likely to be incorrect: a plugin (`'cleanup'`) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
https://github.com/rollup/rollup/wiki/Troubleshooting#sourcemap-is-likely-to-be-incorrect

From the documentation in the link:

> You'll see this warning if you generate a sourcemap with your bundle (`sourceMap: true` or `sourceMap: 'inline'`) but you're using one or more plugins that transformed code without generating a sourcemap for the transformation.
>
> Usually, a plugin will only omit the sourcemap if it (the plugin, not the bundle) was configured with `sourceMap: false` – so all you need to do is change that. If the plugin doesn't generate a sourcemap, consider raising an issue with the plugin author.

**Comment by aMarCruz** [comment]
@joelpurra,
This issue seems to be related to some plugin optimizations and (perhaps) changes to the rollup API.
In the next few days I will study your code to find the solution.
Thanks for your feedback.

**Comment by joelpurra** [comment]
@aMarCruz: ah, yes, that might be it. Also, today I found out that the same warning shows up for `comments: false`, which might be easier to test.

Not sure if it's related but have seen potential side-effects in other libraries, in particular `rollup-plugin-license` which I installed the same day: https://github.com/mjeanroy/rollup-plugin-license/issues/6

Thanks for looking in to it =)
