### ISSUE TITLE
Empty line after deleting comment

### ISSUE THREAD

**Issue by nikolay-borzov** [aMarCruz/rollup-plugin-cleanup#6]
Is it possible to remove an empty line that appears after removing a comment?

Consider config:
```js
cleanup({
  comments: [/^\*-/],
  maxEmptyLines: 1
})
```
Code:
```js
const helpers = {
/**
 * Very big comment explaning method purpose
 */
 findThing() { ... }
}
```
And result is:
```js
const helpers = {

 findThing() { ... }
}
```

**Comment by aMarCruz** [comment]
@nikolay-borzov , please attach the source code, I will try to fix this.

**Comment by nikolay-borzov** [comment]
Sure. Here is a repo
https://github.com/nikolay-borzov/rollup-js-api-test.git
```
npm run build-cli
```
Look at dist/bundle.js

**Comment by aMarCruz** [comment]
@nikolay-borzov , maxEmptyLines defines the maximum number of lines to kepp after deleting a comment, so in the the config you must use `maxEmptyLines:0` to remove all the empty lines:

```js
(function () {
'use strict';

console.log('Module 1')

console.log('Module 2')

console.log('Main module');
const helpers = {
  findThis() {
    return [1,2]
  },
  findThat() {
    return [4,5]
  }
};
console.log(helpers.findThis());
console.log(helpers.findThat());

}());
```

NOTE: the remaining empty lines are placed by rollup after cleanup and I have no control over this, maybe in a future version I'll support post-procesing.

Closing this issue now, thanks for your feedback.

**Comment by nikolay-borzov** [comment]
I see, Rollup adds an empty line between modules - it's not a problem. I want to leave existing empty lines (for structuring the code), but remove particular comments as if they have never been here. Perhaps I should look into the plugin to understand how it works.

Thanks!

**Comment by aMarCruz** [comment]
mmm... this plugin is using Acorn, so there's no control over the comment' surrounding text.
See the old [rmcomms](https://github.com/aMarCruz/rmcomms), maybe its code will be usefull for you.
