### ISSUE TITLE
feature request: removing arbitrary chunks of code

### ISSUE THREAD

**Issue by revelt** [aMarCruz/rollup-plugin-cleanup#9]
hello!
First of all thanks for this plugin.
It's awesome but sometimes my `console.log`s need an extra calculation and I need a way to delete those lines of code too.

Solution would be either 
* adding an extra options item where user could provide regex and this plugin would delete all findings of that regex, OR
* at least proprietary, hard-coded comment in the code à la `//----CLEANUP DELETE FROM` and `//----CLEANUP DELETE TO`

...or something else...

But I'd prefer the regex way.

Maintainers, would you consider adding such feature?

**Comment by aMarCruz** [comment]
@revelt thanks and sorry by the delay.

rollup-plugin-cleanup preserves comments by exclusion, but I think this can be done with [rollup-plugin-jscc](https://github.com/aMarCruz/rollup-plugin-jscc).

With jscc if you want to delete a given code-block based in some condition (ex. _CLEANUP) you do:
```js
//#if _CLEANUP
//
// you temporary code here
//
//#endif
```
_CLEANUP can be defined in your rollup config or by code:
```js
import { rollup } from 'rollup';
import jscc from 'rollup-plugin-jscc';

rollup({
  entry: 'src/main.js',
  plugins: [
    jscc({
      values: { _CLEANUP: true }
    })
  ]
}).then(...)
```

**Comment by revelt** [comment]
@aMarCruz Brilliant! Thank you! Closing.
